.PHONY: migration db
migration:
	cd ./SolarCoffee.Data && dotnet-ef --startup-project ../SolarCoffee.Web migrations add ${mname} && cd ..
db:
	cd ./SolarCoffee.Data && dotnet-ef --startup-project ../SolarCoffee.Web database update && cd ..